server:
  port: 8082

spring:
  application:
    name: employee-service

  config:
    import: "optional:configserver:http://localhost/8088"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/